openapi: 3.0.1
info:
  title: UPS Track Alert API
  termsOfService: 'https://www.ups.com/upsdeveloperkit/assets/html/serviceAgreement.html'
  version: ''
servers:
  - url: 'https://onlinetools.ups.com/api/'
    description: UPS Production Oauth.
  - url: 'https://wwwcie.ups.com/api/'
    description: >-
      UPS Production CIE Oauth. This is for integration testing only and it will
      not create any subscription.
security:
  - oauth2: []
tags:
  - name: UPSTrackAlert_other
    x-displayName: Methods
paths:
  '/track/{version}/subscription/{type}/package':
    post:
      description: >-
        The UPS Track Alert API provides best in-class package tracking
        visibility with near real time event updates for an improved customer
        experience and stream line logistic management.

        Updates are pushed to the user as soon as available with no constant
        polling required, thereby improving operational efficiency.


        Key Business Values:

        - **Enhanced Customer Experience**: Near Real-time tracking information
        increases transparency, leading to higher customer satisfaction and
        trust.

        - **Operational Efficiency**: Eliminates the necessity for continuous
        polling, thus saving computational resources and improving system
        responsiveness.

        - **Data-Driven Decision Making**: Access to timely data can help
        businesses optimize their supply chain and make informed logistics
        decisions.

        - **Optimizing Cash Flow Through Near Real-Time Delivery Tracking**:
        Improve cash flow by knowing the deliveries occurred in near real time.

        - **Mitigating Fraud and Theft through Near Real-Time Package Status
        Monitoring**: Reduce fraud and theft by knowing the status of the
        package.

        <br /><a
        href="https://developer.ups.com/api/reference/trackalert/product-info"
        target="_blank">Product Info</a><br /><a
        href="https://developer.ups.com/api/reference/trackalert/error-codes"
        target="_blank">Errors</a>
      summary: UPS Track Alert API
      operationId: processSubscriptionTypeForTrackingNumber
      parameters:
        - name: version
          in: path
          description: 'API Version, e.g. v1'
          required: true
          schema:
            type: string
        - name: type
          in: path
          required: true
          description: >
            - 'Standard' - Represents a standard subscription type that provides
            near real time updates on tracking status.
          schema:
            type: string
            enum:
              - standard
        - name: transId
          in: header
          description: An identifier unique to the request.
          required: true
          schema:
            type: string
        - name: transactionSrc
          in: header
          description: Identifies the client/source application that is calling.
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrackSubsServiceRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrackSubsServiceResponse'
              examples:
                PartialSuccessExample:
                  description: >-
                    Example response that contains valid tracking number for
                    which subscription created and invalid tracking numbers.
                  value:
                    validTrackingNumbers:
                      - 1Z12345678912345560
                    invalidTrackingNumbers:
                      - 1Z1234567$8
                CompleteSuccessExample:
                  description: >-
                    Example response that contains valid tracking numbers for
                    which subscription created.
                  value:
                    validTrackingNumbers:
                      - 1Z12345678912345560
        '400':
          description: Invalid Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrackSubsServiceErrorResponse'
              example:
                response:
                  errors:
                    - code: VSS300
                      message: >-
                        Locale is required. The Subscription request has been
                        rejected.
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                errors:
                  - code: UJ0001
                    message: Invalid token or token is not present.
        '404':
          description: URL does not exist or resource not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                errors:
                  - code: '404'
                    message: The requested resource was not found.
        '405':
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                errors:
                  - code: '405'
                    message: The requested method is not allowed for this resource.
        '500':
          description: Internal Server Error
components:
  securitySchemes:
    oauth2:
      type: oauth2
      description: |
        "Find your Client ID and Secret on your app info page. <br/> 
         1. Select \\\"Try It\\\" <br/>  
         2. In the Security section enter your Client ID and Secret.<br/> 
         3. Select \\\"Request Token\\\"<br/> 
         4. Enter any additional information in the Body and Parameters sections.<br/> 
         5. Select \\\"Send\\\" to execute your API request"
      flows:
        clientCredentials:
          x-tokenEndpointAuthMethod: client_secret_basic
          tokenUrl: 'https://onlinetools.ups.com/security/v1/oauth/token'
          scopes: {}
  schemas:
    Destination:
      type: object
      required:
        - url
        - credentialType
        - credential
      properties:
        url:
          type: string
          format: url
          description: >
            It is an HTTP-based callback end point that is exposed by the client
            to receive event notification. This endpoint must be operational
            arround the clock to ensure no event notifications are missed.

            If this endpoint is not continuously available, incoming events will
            be lost.
        credentialType:
          type: string
          description: >-
            It is an open-entry field that indicates type of credentials
            supported by the client.
          example: Bearer
        credential:
          type: string
          description: >-
            It is an opaque string meant for client authentication. If for any
            reason this credential changes then any event notification will fail
            until a new subscription is made.
      description: >-
        The destination container related to the clients endpoint API. To which
        messages would be sent on an event on the package.
    TrackSubsServiceRequest:
      required:
        - locale
        - countryCode
        - trackingNumberList
        - destination
      type: object
      properties:
        locale:
          type: string
          description: >-
            Locale setting is composed of language code and country code,
            separated by an underscore. This field is reserved for future use.
          pattern: '^[a-z]{2}_[A-Z]{2}$'
          example: en_US
        countryCode:
          type: string
          description: Represents the country code. This field is reserved for future use.
          example: US
        trackingNumberList:
          type: array
          description: Represents list of tracking numbers in request.
          maxItems: 100
          example:
            - 1ZCIETST0111111114
            - 1ZCIETST0422222228
          items:
            type: string
            pattern: '^1Z[0-9A-Z]{16}$'
            description: >-
              Represents tracking numbers starting with '1Z', followed by 16
              alphanummeric characters in request.
        scanPreference:
          type: array
          description: >-
            Represents scan/event preferences for the subscription endpoint,
            Place holder for Future use.
          items:
            type: string
            description: >-
              Represents scan/event preferences for the subscription endpoint,
              Place holder for Future use.
        destination:
          $ref: '#/components/schemas/Destination'
    ErrorMessage:
      type: object
      properties:
        code:
          type: string
          description: The error code.
          example: VSS300
        message:
          type: string
          description: The error message.
          example: Locale is required. The Subscription request has been rejected.
      description: The error response containing any errors that occurred
    TrackSubsServiceResponse:
      type: object
      properties:
        validTrackingNumbers:
          type: array
          description: List of tracking numbers with successful subscription created.
          items:
            type: string
          example:
            - 1Z1234567891234556
            - 1ZABCDEFH91234556
        invalidTrackingNumbers:
          type: array
          description: >-
            List of tracking numbers associated with errors preventing
            subscription creation.
          items:
            type: string
          example:
            - 1Z1234567$8
    TrackSubsServiceErrorResponse:
      type: object
      properties:
        response:
          $ref: '#/components/schemas/ErrorResponse'
        invalidTrackingNumbers:
          $ref: >-
            #/components/schemas/TrackSubsServiceResponse/properties/invalidTrackingNumbers
      required:
        - response
    Response:
      type: object
      properties:
        errors:
          type: array
          description: The error response containing any errors that occurred.
          items:
            $ref: '#/components/schemas/ErrorMessage'
    ErrorResponse:
      type: object
      properties:
        response:
          $ref: '#/components/schemas/ErrorResponseWrapper'
    ErrorResponseWrapper:
      title: ErrorResponseWrapper
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    Error:
      title: Error
      type: object
      properties:
        code:
          type: string
        message:
          type: string